---
- name: this playbook install packages
  hosts: all
  become: true
  #  gather_facts: no
  tasks:
  - name: install packages
    yum:
      name: httpd
      state: installed
#    notify: start httpd service
    when: ansible_os_family == "RedHat"
    tags: install_apache

#  handlers:
  - name: start apache
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
    tags: start_apache

  - name: install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666

