---
- name: this playbook is to setup tomcat server
  hosts: all
  become: true
  tasks:
  - name: install java
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on ubuntu
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat packages
    get_url:
      url: https://apache.mirrors.nublue.co.uk/tomcat/tomcat-8/v8.5.55/bin/apache-tomcat-8.5.55.tar.gz
      dest: /opt

  - name: Unarchive a file that is already on the remote machine
    unarchive:
      src: /opt/apache-tomcat-8.5.55.tar.gz
      dest: /opt
      remote_src: yes

  - name: add execution permission on startup.ssh
    file:
      path: /opt/apache-tomcat-8.5.55/bin/startup.sh
      mode: 0777

  - name: start tomcat services
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.55/bin

